from __future__ import annotations


# Categorias publicadas pela Pluggy em setembro/2026. A categoria original
# continua preservada em Transaction.source_category_name; este catálogo serve
# apenas para apresentar e organizar a classificação local em português-BR.
PLUGGY_CATEGORY_PT_BR: dict[str, str] = {
    "Income": "Receitas",
    "Salary": "Salário",
    "Retirement": "Aposentadoria",
    "Entrepreneurial activities": "Atividades empreendedoras",
    "Government aid": "Benefícios governamentais",
    "Non-recurring income": "Receitas não recorrentes",
    "Loans and Financing": "Empréstimos e financiamentos",
    "Late payment and overdraft costs": "Juros de atraso e cheque especial",
    "Interests charged": "Juros cobrados",
    "Loans": "Empréstimos",
    "Financing": "Financiamentos",
    "Real estate financing": "Financiamento imobiliário",
    "Vehicle Financing": "Financiamento de veículo",
    "Student loan": "Financiamento estudantil",
    "Investments": "Investimentos",
    "Automatic investment": "Investimento automático",
    "Fixed income": "Renda fixa",
    "Mutual funds": "Fundos de investimento",
    "Variable income": "Renda variável",
    "Margin": "Margem",
    "Proceeds interests and dividends": "Rendimentos, juros e dividendos",
    "Pension": "Previdência",
    "Same person transfer": "Transferência entre contas da mesma pessoa",
    "Same person transfer - Cash": "Transferência própria - Dinheiro",
    "Same person transfer - PIX": "Transferência própria - PIX",
    "Same person transfer - TED": "Transferência própria - TED",
    "Transfers": "Transferências",
    "Transfer - Bank slip (Boleto)": "Transferência - Boleto",
    "Transfer - Cash": "Transferência - Dinheiro",
    "Transfer - Check": "Transferência - Cheque",
    "Transfer - DOC": "Transferência - DOC",
    "Transfer - Foreign exchange": "Transferência - Câmbio",
    "Transfer - Internal": "Transferência interna",
    "Transfer - PIX": "Transferência - PIX",
    "Transfer - TED": "Transferência - TED",
    "Credit card payment": "Pagamento de cartão de crédito",
    "Third-party transfers": "Transferências para terceiros",
    "Bank slip": "Boleto",
    "Debt card": "Cartão de débito",
    "Debit card": "Cartão de débito",
    "DOC": "DOC",
    "PIX": "PIX",
    "TED": "TED",
    "Legal obligations": "Obrigações legais",
    "Blocked balances": "Valores bloqueados",
    "Alimony": "Pensão alimentícia",
    "Services": "Serviços",
    "Telecommunications": "Telecomunicações",
    "Internet": "Internet",
    "Mobile": "Celular",
    "TV": "TV",
    "Education": "Educação",
    "Online Courses": "Cursos on-line",
    "University": "Universidade",
    "School": "Escola",
    "Kindergarten": "Educação infantil",
    "Wellness and fitness": "Bem-estar e atividade física",
    "Gyms and fitness centers": "Academias e centros de treinamento",
    "Sports practice": "Prática esportiva",
    "Wellness": "Bem-estar",
    "Tickets": "Ingressos",
    "Stadiums and arenas": "Estádios e arenas",
    "Landmarks and museums": "Pontos turísticos e museus",
    "Cinema, theater and concerts": "Cinema, teatro e shows",
    "Shopping": "Compras",
    "Online shopping": "Compras on-line",
    "Electronics": "Eletrônicos",
    "Pet supplies and vet": "Produtos pet e veterinário",
    "Clothing": "Vestuário",
    "Kids and toys": "Crianças e brinquedos",
    "Bookstore": "Livraria",
    "Sports goods": "Artigos esportivos",
    "Office Supplies": "Material de escritório",
    "Cashback": "Cashback",
    "Digital services": "Serviços digitais",
    "Gaming": "Jogos",
    "Video streaming": "Streaming de vídeo",
    "Music streaming": "Streaming de música",
    "Groceries": "Supermercado",
    "Food and drinks": "Alimentação e bebidas",
    "Eating out": "Restaurantes e alimentação fora de casa",
    "Food delivery": "Delivery de comida",
    "Travel": "Viagens",
    "Airport and airlines": "Aeroportos e companhias aéreas",
    "Accommodation": "Hospedagem",
    "Mileage programs": "Programas de milhas",
    "Bus tickets": "Passagens de ônibus",
    "Donations": "Doações",
    "Gambling": "Apostas",
    "Lottery": "Loteria",
    "Online bet": "Apostas on-line",
    "Taxes": "Impostos",
    "Income taxes": "Imposto de renda",
    "Taxes on investments": "Impostos sobre investimentos",
    "Tax on financial operations": "IOF / imposto sobre operações financeiras",
    "Bank fees": "Tarifas bancárias",
    "Account fees": "Tarifas de conta",
    "Wire transfer fees and ATM fees": "Tarifas de transferências e saques",
    "Credit card fees": "Tarifas de cartão de crédito",
    "Housing": "Moradia",
    "Rent": "Aluguel",
    "Houseware": "Artigos para casa",
    "Urban land and building tax": "IPTU",
    "Utilities": "Contas residenciais",
    "Water": "Água",
    "Electricity": "Energia elétrica",
    "Gas": "Gás",
    "Healthcare": "Saúde",
    "Dentist": "Dentista",
    "Pharmacy": "Farmácia",
    "Optometry": "Ótica e optometria",
    "Hospital clinics and labs": "Hospitais, clínicas e laboratórios",
    "Transportation": "Transporte",
    "Taxi and ride-hailing": "Táxi e transporte por aplicativo",
    "Public transportation": "Transporte público",
    "Car rental": "Aluguel de veículos",
    "Bicycle": "Bicicleta",
    "Automotive": "Automotivo",
    "Gas stations": "Combustível / postos",
    "Parking": "Estacionamento",
    "Tolls and in-vehicle payment": "Pedágios e pagamentos veiculares",
    "Vehicle ownership taxes and fees": "Impostos e taxas de veículos",
    "Vehicle maintenance": "Manutenção de veículos",
    "Traffic tickets": "Multas de trânsito",
    "Insurance": "Seguros",
    "Life insurance": "Seguro de vida",
    "Home Insurance": "Seguro residencial",
    "Health insurance": "Plano ou seguro de saúde",
    "Vehicle insurance": "Seguro de veículo",
    "Leisure": "Lazer",
    "Other": "Outros",
}


_PLUGGY_CATEGORY_PT_BR_CASEFOLD = {
    key.casefold(): value
    for key, value in PLUGGY_CATEGORY_PT_BR.items()
}


def translate_pluggy_category(name: str | None) -> str:
    normalized = " ".join(str(name or "").split())
    if not normalized:
        return ""
    return PLUGGY_CATEGORY_PT_BR.get(
        normalized,
        _PLUGGY_CATEGORY_PT_BR_CASEFOLD.get(normalized.casefold(), normalized),
    )
